export const COLOR_WHITE = '#FFF'
export const COLOR_CONTESA = '#C97164'
export const COLOR_QUICKSAND = '#BC978C'
export const COLOR_QUARTER_SPANISH_WHITE = '#F9F1E7'
export const COLOR_CADET_BLUE = '#5F9EA0'
export const COLOR_BRIGHT_GRAY = '#37384C'
export const COLOR_BLACK = '#000'
